// love-receipt pool — English, tone-tagged for the balanced shuffle.
// tones: giggle | petty | delulu | real-life | almost-moment | tender
//
// Fields (id/text/price/tone/lang) map straight onto the receipt's line model:
// `text` + `price` are what render; `tone` is backend-only (drives the balanced
// shuffle, never shown); `lang` future-proofs a Hinglish pool drop. // REVISIT:
// add a Hinglish pool beside this one (same shape, lang: 'hi') when ready.

export type Tone =
  | 'giggle'
  | 'petty'
  | 'delulu'
  | 'real-life'
  | 'almost-moment'
  | 'tender';

/** One curated pool line. Renders as a receipt line (text + price); `tone` is
 *  invisible to users and only steers the balanced shuffle. */
export interface PoolLine {
  id: string;
  text: string;
  price: string;
  tone: Tone;
  lang: 'en';
}

export const LOVE_RECEIPT_POOL: PoolLine[] = [
  {
    id: 'lr-001',
    text: `your hoodie (im NOT returning)`,
    price: `kept`,
    tone: 'petty',
    lang: 'en',
  },
  {
    id: 'lr-002',
    text: `47× futures i planned w u`,
    price: `EMI`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-003',
    text: `the audacity to look this good`,
    price: `santoor tax`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-004',
    text: `you leaned in… to grab your phone`,
    price: `void`,
    tone: 'almost-moment',
    lang: 'en',
  },
  {
    id: 'lr-005',
    text: `you "didn't like him" (the guy said hi, once)`,
    price: `mine`,
    tone: 'petty',
    lang: 'en',
  },
  {
    id: 'lr-006',
    text: `you got grumpy 'cause i replied late (i was asleep)`,
    price: `sulk tax`,
    tone: 'petty',
    lang: 'en',
  },
  {
    id: 'lr-007',
    text: `you introduced me with your hand on my back (proud)`,
    price: `claimed`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-008',
    text: `told mumma "just a friend" (my face lied)`,
    price: `busted`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-009',
    text: `100 arguments i won in the shower`,
    price: `champ`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-010',
    text: `you tucked my hair behind my ear`,
    price: `₹101`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-011',
    text: `you called me by that nickname`,
    price: `1 of 1`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-012',
    text: `you wore the colour i said i liked`,
    price: `noted`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-013',
    text: `you said "drive safe"`,
    price: `₹143`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-014',
    text: `you asked "khaana khaya?"`,
    price: `∞`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-015',
    text: `you stayed on call till i fell asleep`,
    price: `overtime`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-016',
    text: `hoodie i stole from you, still smells like you`,
    price: `stolen`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-017',
    text: `quietly hoping you're my last first-everything`,
    price: `pre-order`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-018',
    text: `i sleep better since you`,
    price: `8 hrs`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-019',
    text: `i want all your boring Tuesdays, every one`,
    price: `booked`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-020',
    text: `home stopped being a place — it's you`,
    price: `priceless`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-021',
    text: `you make me feel like i'm not "too much"`,
    price: `enough`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-022',
    text: `boring with you is still my favourite thing`,
    price: `5 stars`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-023',
    text: `you held my hand crossing the road (i'm 24 btw)`,
    price: `VIP`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-024',
    text: `i practiced your last name with mine (tell no one)`,
    price: `final`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-025',
    text: `you became the first person i tell good news to`,
    price: `1st call`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-026',
    text: `you matched your shirt to my dress on purpose`,
    price: `matched`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-027',
    text: `metro was packed, you became my wall`,
    price: `shield`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-028',
    text: `you remembered what i wore on day one`,
    price: `filed`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-029',
    text: `you said "i've got you" and i believed it`,
    price: `settled`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-030',
    text: `i'd pick you in every version of this life`,
    price: `any life`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-031',
    text: `you kissed my scars like they were nothing`,
    price: `fearless`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-032',
    text: `you make forever sound too short`,
    price: `encore`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-033',
    text: `you hold my bag, phone, AND dupatta`,
    price: `cloakroom`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-034',
    text: `you play with my fingers without noticing`,
    price: `fidget`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-035',
    text: `you finish my sentences (annoying, correct)`,
    price: `same brain`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-036',
    text: `you're my first thought before the alarm`,
    price: `pre-dawn`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-037',
    text: `i think in "we" now without trying`,
    price: `auto`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-038',
    text: `loving you is the easiest hard thing`,
    price: `finally`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-039',
    text: `you let me "win" the argument`,
    price: `charity`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-040',
    text: `you waited at my gate till i got inside`,
    price: `watched in`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-041',
    text: `you keep your hand on my knee while driving`,
    price: `anchored`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-042',
    text: `i didn't know tired could feel this safe`,
    price: `at rest`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-043',
    text: `you're the first good thing that stayed`,
    price: `lifer`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-044',
    text: `"five more minutes" — it has been an hour`,
    price: `overdue`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-045',
    text: `you sulked 'cause a guy in a reel made me laugh harder than you`,
    price: `petty`,
    tone: 'petty',
    lang: 'en',
  },
  {
    id: 'lr-046',
    text: `you feel less like a risk and more like a roof`,
    price: `shelter`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-047',
    text: `i want to scroll reels next to you till we're old`,
    price: `long lease`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-048',
    text: `you're my "guess what happened today"`,
    price: `first dibs`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-049',
    text: `you're who i look for the second i walk in`,
    price: `radar`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-050',
    text: `you're the reason my camera roll is 90% nonsense`,
    price: `archive`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-051',
    text: `you're the plan even when there's no plan`,
    price: `default`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-052',
    text: `you took 7 bad pics to get me one good one`,
    price: `burst mode`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-053',
    text: `you waited outside the temple holding my sandals`,
    price: `guard duty`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-054',
    text: `you slow your walk so i can keep up`,
    price: `paced`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-055',
    text: `you let me cry without rushing to fix it`,
    price: `held`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-056',
    text: `i looked for red flags and found dimples`,
    price: `compromised`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-057',
    text: `i became one of those people who smiles at their phone`,
    price: `tragic`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-058',
    text: `every couple reel became our reel`,
    price: `tagged`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-059',
    text: `you reacted ❤️ and i built a future`,
    price: `under construction`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-060',
    text: `i sent a risky text and threw my phone away`,
    price: `launched`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-061',
    text: `your "hmm" caused three business days of overthinking`,
    price: `processing`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-062',
    text: `i said "do whatever you want"`,
    price: `trap card`,
    tone: 'petty',
    lang: 'en',
  },
  {
    id: 'lr-063',
    text: `this reel reminded me of you`,
    price: `all of them`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-064',
    text: `i saw an old couple and thought "us"`,
    price: `projection`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-065',
    text: `i imagined us arguing about curtains`,
    price: `future planning`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-066',
    text: `you carried my emotional support water bottle`,
    price: `auxiliary unit`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-067',
    text: `i miss you in the middle of perfectly good days`,
    price: `recurring`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-068',
    text: `you followed a new person and i opened a case file`,
    price: `compliance review`,
    tone: 'petty',
    lang: 'en',
  },
  {
    id: 'lr-069',
    text: `you got a haircut and expected me to stay normal`,
    price: `impossible request`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-070',
    text: `you laughed at someone else's joke first`,
    price: `complaint filed`,
    tone: 'petty',
    lang: 'en',
  },
  {
    id: 'lr-071',
    text: `i started saying things you say`,
    price: `software update`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-072',
    text: `i said i wasn't jealous`,
    price: `false declaration`,
    tone: 'petty',
    lang: 'en',
  },
  {
    id: 'lr-073',
    text: `your honour, i fear i have feelings`,
    price: `court record`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-074',
    text: `my friends know too much about you`,
    price: `information leak`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-075',
    text: `i imagined your reaction before telling the story`,
    price: `pre-approved`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-076',
    text: `i couldn't wait to tell you about it`,
    price: `express delivery`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-077',
    text: `i saw your name and my mood changed`,
    price: `instant transfer`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-078',
    text: `i reread old messages for no reason`,
    price: `archived`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-079',
    text: `i know exactly which photo of me is your favourite`,
    price: `memorized`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-080',
    text: `i checked if you'd seen my story`,
    price: `delivery confirmation`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-081',
    text: `you became the person i save things for`,
    price: `bookmarked`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-082',
    text: `somehow life got easier with you in it`,
    price: `system upgrade`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-083',
    text: `you became my favourite part of ordinary days`,
    price: `featured item`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-084',
    text: `you looked at my lips for a second too long`,
    price: `flagged`,
    tone: 'almost-moment',
    lang: 'en',
  },
  {
    id: 'lr-085',
    text: `your "come here" voice`,
    price: `premium feature`,
    tone: 'almost-moment',
    lang: 'en',
  },
  {
    id: 'lr-086',
    text: `you pulled me closer during a photo`,
    price: `adjusted manually`,
    tone: 'almost-moment',
    lang: 'en',
  },
  {
    id: 'lr-087',
    text: `eye contact lasted longer than recommended`,
    price: `safety violation`,
    tone: 'almost-moment',
    lang: 'en',
  },
  {
    id: 'lr-088',
    text: `did the seva, asked bhagwan to fast-track u home`,
    price: `fate tax included`,
    tone: 'delulu',
    lang: 'en',
  },
  {
    id: 'lr-089',
    text: `i function fine, i function better with u here`,
    price: `balance overdue`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-090',
    text: `u feel like a home i haven't moved into yet`,
    price: `lease pending`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-091',
    text: `you wore my initial around your neck`,
    price: `claimed`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-092',
    text: `talking to you after a really long day`,
    price: `reset`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-093',
    text: `you stopped mid-walk to pick me a flower`,
    price: `detour approved`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-094',
    text: `your random forehead kisses`,
    price: `instant calm`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-095',
    text: `my fingers wrapped around your bicep`,
    price: `default setting`,
    tone: 'real-life',
    lang: 'en',
  },
  {
    id: 'lr-096',
    text: `nonchalant for everyone else, pookie for me`,
    price: `exclusive access`,
    tone: 'giggle',
    lang: 'en',
  },
  {
    id: 'lr-097',
    text: `my bsf, loml, my everything`,
    price: `one-stop shop`,
    tone: 'tender',
    lang: 'en',
  },
  {
    id: 'lr-098',
    text: `if we were both words, you'd be my meaning`,
    price: `complete`,
    tone: 'tender',
    lang: 'en',
  },
];

// Lines that must never land in the same draw (mutually exclusive).
// Easy to extend — just add more [id, id] pairs.
export const COLLISION_PAIRS: [string, string][] = [
  ['lr-001', 'lr-016'], // both hoodie lines
  ['lr-019', 'lr-022'], // both "boring" lines
];

// Hand-picked default starting set — loads before any regenerate.
// Spread: delulu / petty / real-life / tender. All distinct prices, no collisions.
export const DEFAULT_STARTING_IDS: string[] = [
  'lr-061',
  'lr-045',
  'lr-027',
  'lr-021',
];

// Tone counts (for tuning the shuffle):
//   tender         35
//   real-life      19
//   giggle         18
//   delulu         13
//   petty           8
//   almost-moment   5
