export const testMessages = [
  "the way you say 'arre' when you're confused",
  'how you eat the corners of parathas first',
  'your face when you taste something for the first time',
  'the way you fall asleep in the car always',
  'how you remember every single thing I tell you',
  "the little hum you do when you're concentrating",
  'how you always know where my keys are',
  'the way you laugh at your own jokes before finishing them',
  'how seriously you take playlist curation',
  "your texts when you're sleepy",
  'the way you photograph your food before eating',
  'how you defend your favorite movies',
  'your handwriting on grocery lists',
  "the way you say my name when you're tired",
  "how you make tea like it's a ritual",
  'the playlists you make for long drives',
  'the way you describe books you love',
  'how you always notice the dog before the person walking it',
  "your voice notes when you're walking",
  'the way you say good morning',
] as const;
